version: "3.8"

volumes:
  postgres:

services:
  server:
    tty: true
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      LOG_LEVEL: debug
      LOG_TEXTLOGGING: "true"
      PORT: 8000
      DB_ADDR: postgres:5432
      ENABLE_CORS: "true"
      
  postgres:
    image: postgres:13
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "godb"
      POSTGRES_USER: "am"
      POSTGRES_PASSWORD: postgres
